### PR TITLE
Add cache for file list

### PR DESCRIPTION
**Pull request by danyang685**

### CODE REVIEW

**Comment by skyzh** [comment]
Thank you for your PR! This change is impressive, as it will boost download speed when using module mode. But there's an edge case to consider. Some courses are set to disable file functionality, which means that we cannot get file list. This PR can be merged if this is taken into consideration.

**Review by skyzh — COMMENTED** [review]
Consider edge case.

**Comment by danyang685** [comment]
It is fixed now.

**Review by skyzh — APPROVED** [review]
`__contains__` can be changed into `in`. I'll add it later.

**Pull request merged**
